export const Actions = {
  GET_STOCK: "GET_STOCK",
  GET_STOCK_SUCCESS: "GET_STOCK_SUCCESS",
  GET_STOCK_FAIL: "GET_STOCK_FAIL",

  GET_STOCK_CHART: "GET_STOCK_CHART",
  GET_STOCK_CHART_SUCCESS: "GET_STOCK_CHART_SUCCESS",
  GET_STOCK_CHART_FAIL: "GET_STOCK_CHART_FAIL",

  GET_SYMBOLS: "GET_SYMBOLS",
  GET_SYMBOLS_SUCCESS: "GET_SYMBOLS_SUCCESS",
  GET_SYMBOLS_FAIL: "GET_SYMBOLS_FAIL",

  SET_SYMBOL: "SET_SYMBOL",

  TOGGLE_FAVORITE: "TOGGLE_FAVORITE",
  GET_FAVORITES: "GET_FAVORITES",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  GET_FAVORITES_FAIL: "GET_FAVORITES_FAIL",
  CLEAR_FAVORITES: "CLEAR_FAVORITES",

  SHOW_AUTOSUGGEST: "SHOW_AUTOSUGGEST",

  GET_GAINERS: "GET_GAINERS",
  GET_GAINERS_SUCCESS: "GET_GAINERS_SUCCESS",
  GET_GAINERS_FAIL: "GET_GAINERS_FAIL",

  GET_LOSERS: "GET_LOSERS",
  GET_LOSERS_SUCCESS: "GET_LOSERS_SUCCESS",
  GET_LOSERS_FAIL: "GET_LOSERS_FAIL",

  GET_MOST_ACTIVE: "GET_MOST_ACTIVE",
  GET_MOST_ACTIVE_SUCCESS: "GET_MOST_ACTIVE_SUCCESS",
  GET_MOST_ACTIVE_FAIL: "GET_MOST_ACTIVE_FAIL",

  GET_NEWS_BLOOMBERG: "GET_NEWS_BLOOMBERG",
  GET_NEWS_BLOOMBERG_SUCCESS: "GET_NEWS_BLOOMBERG_SUCCESS",
  GET_NEWS_BLOOMBERG_FAIL: "GET_NEWS_BLOOMBERG_FAIL",
  GET_NEWS_BUSINESS_INSIDER: "GET_NEWS_BUSINESS_INSIDER",
  GET_NEWS_BUSINESS_INSIDER_SUCCESS: "GET_NEWS_BUSINESS_INSIDER_SUCCESS",
  GET_NEWS_BUSINESS_INSIDER_FAIL: "GET_NEWS_BUSINESS_INSIDER_FAIL",
  GET_NEWS_FINANCIAL_POST: "GET_NEWS_FINANCIAL_POST",
  GET_NEWS_FINANCIAL_POST_SUCCESS: "GET_NEWS_FINANCIAL_POST_SUCCESS",
  GET_NEWS_FINANCIAL_POST_FAIL: "GET_NEWS_FINANCIAL_POST_FAIL",
  GET_NEWS_FORTUNE: "GET_NEWS_FORTUNE",
  GET_NEWS_FORTUNE_SUCCESS: "GET_NEWS_FORTUNE_SUCCESS",
  GET_NEWS_FORTUNE_FAIL: "GET_NEWS_FORTUNE_FAIL",
  GET_NEWS_WALL_STREET_JOURNAL: "GET_NEWS_WALL_STREET_JOURNAL",
  GET_NEWS_WALL_STREET_JOURNAL_SUCCESS: "GET_NEWS_WALL_STREET_JOURNAL_SUCCESS",
  GET_NEWS_WALL_STREET_JOURNAL_FAIL: "GET_NEWS_WALL_STREET_JOURNAL_FAIL",

  GET_CALENDAR_IPO: "GET_CALENDAR_IPO",
  GET_CALENDAR_IPO_SUCCESS: "GET_CALENDAR_IPO_SUCCESS",
  GET_CALENDAR_IPO_FAIL: "GET_CALENDAR_IPO_FAIL",
  GET_CALENDAR_EARNINGS: "GET_CALENDAR_EARNINGS",
  GET_CALENDAR_EARNINGS_SUCCESS: "GET_CALENDAR_EARNINGS_SUCCESS",
  GET_CALENDAR_EARNINGS_FAIL: "GET_CALENDAR_EARNINGS_FAIL",
  GET_CALENDAR_ECONOMIC: "GET_CALENDAR_ECONOMIC",
  GET_CALENDAR_ECONOMIC_SUCCESS: "GET_CALENDAR_ECONOMIC_SUCCESS",
  GET_CALENDAR_ECONOMIC_FAIL: "GET_CALENDAR_ECONOMIC_FAIL",

  GET_RECOMMENDATION: "GET_RECOMMENDATION",
  GET_RECOMMENDATION_SUCCESS: "GET_RECOMMENDATION_SUCCESS",
  GET_RECOMMENDATION_FAIL: "GET_RECOMMENDATION_FAIL"


};
